language: php

php:
    - 7.4

before_script:
    - pecl install pcov
    - phpenv config-rm xdebug.ini
    - composer global require hirak/prestissimo -o --no-ansi --no-suggest
    - composer update -o --no-ansi --no-suggest
    - composer update -o --no-ansi --no-suggest

script:
    - vendor/bin/phpcs src tests -p --extensions=php --standard=ruleset.xml
    - vendor/bin/phpstan analyse src tests -c ruleset.neon -l 8 --error-format=custom
    - vendor/bin/phpunit tests --coverage-clover build/logs/clover.xml

after_success:
    - vendor/bin/php-coveralls

notifications:
    email: false